services:
  next-ai-draw-io:
    build: .
    image: next-ai-draw-io:v1.0
    container_name: next-ai-draw-io
    ports:
      - "3000:3000"
    environment:
      - AI_PROVIDER=openai
      - AI_MODEL=qwen3.8-flash
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    volumes:
      - ./data:/app/data
    restart: always